### ISSUE TITLE
Dude, save the world trouble; Add a way to escape those separators.

### ISSUE THREAD

**Issue by MarcusJohnson91** [SixArm/usv#4]
Seriously, why repeat the mistakes of CSV

**Comment by joelparkerhenderson** [comment]
Thanks for the feedback. 

We did consider it, for a couple years, and it turns out we never found any real world case of people wanting to embed the USV characters into the data content. Do you have a real world need for it?

When we researched CSV escaping, we found that it solved some needs, yet caused difficulties for other needs. We concluded that CSV escaping is very important because commas are so frequent in real world English text, and that the USV doesn't have this same kind of frequent need.

The escaping can certainly be done as an adjunct, similar to how HTML does it, with ampersand codes, or Unicode \u+dddd codes, etc.

**Comment by joelparkerhenderson** [comment]
For your idea, what do you think about this approach?

* USV for simple and fast, with no escapes

* USVX for extras, such as whitespace trim, backslash escape, final newlines, etc.

**Comment by ptman** [comment]
Doesn't escaping work now?

**Comment by joelparkerhenderson** [comment]
Yes it does-- thanks for the memory jog. I'll close this issue now.
